const themeConfig = {
  customerName: "Jeyabala Jewellery",
  primaryColor: "#2f2483",
  secondaryColor: "#DFB45B",
  splashBackgroundColor: "#ffffff",
  adaptiveIconBackgroundColor: "#ffffff",
  splashLogo: "./assets/images/splashscreen_logo.png",
  icon: "./assets/images/icon.png",
  adaptiveIcon: "./assets/images/adaptive-icon.png",
  bundleIdentifier: "com.nexooai.jeyabalajewellery",
  projectId: "d8571507-0c97-4cbc-9e65-32535f15fa46",
  owner: "mnvgroups07",
  slug: "jeyabalajewellery",
  enableDashboard: false,
  homeVersion: "v2",
  enableHomeV2: true,
  androidVersion: "1.0.0",
  iosVersion: "1.0.0",
  versionCode: 1,
  buildNumber: "1",
  address: "Vathiyar Street, Devakottai, Tamil Nadu 630302",
  mobile: "+919486611921",
  whatsapp: "+919486611921",
  email: "jeyabalajb83@gmail.com",
  website: "https://jeyabalajewellery.com",
  latitude: 9.9482,
  longitude: 78.8258,
  foundationYear: 1995,
  baseUrl: "https://api.prod.jeyabalajewellery.com",
  playStoreUrl: "https://play.google.com/store/apps/details?id=com.nexooai.jeyabalajewellery&hl=en_IN",
  appStoreUrl: "https://apps.apple.com/app/jeyabala-jewellery/id0000000000",
  providerName: "NexooAI Solutions",
  providerUrl: "https://nexooai.com/",
  youtubeUrl: "https://youtu.be/8RAhdn5b9Bw",
};

module.exports = { themeConfig };
