
const themeConfig = {
  customerName: "Kanisaa Jewellery",
  primaryColor: "#a3203a",
  secondaryColor: "#D4AF37",
  splashBackgroundColor: "#a3203a",
  adaptiveIconBackgroundColor: "#a3203a",
  splashLogo: "./assets/images/splashscreen_logo.png",
  icon: "./assets/images/icon.png",
  adaptiveIcon: "./assets/images/adaptive-icon.png",
  bundleIdentifier: "com.nexooai.kanisaajewellerydigigoldsavings",
  projectId: "aeef6800-eac4-4ba3-b14d-a09d7342f537",
  owner: "mnvgroups07",
  slug: "kanisaajewellerydigigold",
  enableDashboard: false,
  homeVersion: "v1",
  enableHomeV2: false,
  androidVersion: "1.0.0",
  iosVersion: "1.0.0",
  versionCode: 1,
  buildNumber: "1",
  address: "Road Fathima Nagar, Mission Quarters, Anchery, Thrissur, Kerala 680005",
  mobile: "+919061803999",
  whatsapp: "+919061803999",
  email: "dcjewellerstcr@gmail.com",
  website: "https://www.dcjewellers.org",
  latitude: 8.427828080550306,
  longitude: 78.02855977120382,
  foundationYear: 2020,
  baseUrl: "https://api.prod.kanisaajewellery.com",
  playStoreUrl: "https://play.google.com/store/apps/details?id=com.nexooai.kanisaajewellerydigigoldsavings&hl=en_IN",
  appStoreUrl: "https://apps.apple.com/us/app/kanisaa-jewellers-gold-diamonds/id6755081937",
};

module.exports = { themeConfig };
